# Generated by Django 5.1.7 on 2025-06-06 08:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
